Orange-OpenSource/ods-charts

- README.md
This PR adds https://ods-charts.netlify.app/ in our README for the users to have access to our documentation.
This PR also adds the Netlify badge showing the status of the _main_ branch deployment, and the npm badge showing the latest released version.
> docs(README): add documentation link and Netlify badge

- docs/README.md
- docs/examples/index.html
- docs/index.html
(NA)
manage relative path when running server locally
- (NA) `test/angular`
- (NA) `test/angular-tour-of-heroes`
- (NA) `test/html`
- (NA) `test/react`
- (NA) `test/vue`
- (NA) `test/examples/bar-line-chart`
- (NA) `test/examples/single-line-chart`
> chore: manage relative path when running server locally

- .github/dependabot.yml
This PR adds a rule for Dependabot:
- each week, the dependencies will be checked for the library
- each month, the dependencies will be checked for each `/test/*` sub-project and the PR should group the updates
This second part is based on [the group rule used by Bootstrap Examples](https://raw.githubusercontent.com/twbs/examples/b2c5286e5e36e33e5655a7e9193c6d224d7f03af/.github/dependabot.yml). I've never tried something like it so let's see if it works once it's merged!
> chore: add Dependabot rules

- test/html/index.html
In the second graph of the test/html/ test, a legend is displayed under the graph title
This legend is not necessary for a chart with one bar
- (NA) `docs/examples`
- (NA) `test/angular`
- (NA) `test/angular-tour-of-heroes`
- (NA) `test/react`
- (NA) `test/vue`
- (NA) `test/examples/bar-line-chart`
- (NA) `test/examples/single-line-chart`
> fix(test): In the third graph of the test test/html/, a legend is displayed under the title

- src/theme/popover/ods-chart-popover-definitions.ts
- src/theme/popover/ods-chart-popover.ts
- test/examples/bar-line-chart/index.html
Closes #146.
Remove useless `tooltipConfine`.
There was an issue using this new option in #107 and there is no need for it anymore after the patch.
Sorry for the issue.
- Bug fix (breaking which fixes an issue)
> Remove `tooltipConfine` option

- docs/examples/bar-chart.html
- docs/examples/bar-line-chart.html
- docs/examples/index.js
- docs/examples/multiple-line-chart.html
- docs/examples/single-line-chart.html
- docs/examples/stacked-bar-chart.html
Closes #169
Set up examples inside iframes to isolate them from the main page CSS and JS.
Simplify a bit the index.js.
Changing the library (could be done separately) to handle larger markups.
Tried my best using webComponents to encapsulate graphs but the JS leaks outside the webcomponent and leads to issues with the js parts, that are called the number of webcomponent inside a page -> Leads to breaking accordions/tooltips, ...
Turning to iframes that encapsulate JS as well but there are some side effects with echarts and our lib right now. The remaining issue can be seen from the 2 last commits of the branch.
Should we have NONE as an option for the theme ?
#169.
Avoid changing the CSS from …
> Docs: isolate charts in `<iframe>`s

- .github/workflows/lint.yml
- src/theme/common/ODS.line-style.broken.ts
Closes #212
This PR adds a GitHub workflow that will enforce the Prettier formatting rules on all files in the repository:
- It will run on every push to the repository
- It will run on every pull request to the repository
- It can be run manually by anyone with write access to the repository
This PR came firstly with few lines added to `src/theme/common/ODS.line-style.broken.ts` in order to make the workflow fail voluntarily, as you can see at https://github.com/Orange-OpenSource/ods-charts/actions/runs/8811608553/job/24185800032?pr=214.
Confirming that everything works correctly, [this modification has been removed](https://github.com/Orange-OpenSource/ods-charts/pull/214/commits/03fe98be29f3e36b998d360bd1b9affe8e922ead), and the workflow is now green.
- New feature (non-breaking change …
> chore(ci): add GitHub workflow to enforce Prettier check

- docs/examples/index.js
NA
Remove `lodash` library import and replace it with common techniques.
Don't forget to check the rendering on Safari
Remove a dependency (good for eco-design, maintenance, etc)
- Refactoring (non-breaking change)
> Docs: Proposal to remove `lodash` import

- src/theme/popover/ods-chart-popover.ts
Closes #157.
Rename variables and add some types to them.
`params` remains `any` since the type might be hard to define and maintain on our side.
Stay close to Typescript
- Refactoring (non-breaking change)
> Lib: Add types and rename variables

- docs/examples/index.js
- src/theme/css-themes/css-themes.ts
- src/theme/legends/ods-chart-legends.ts
- src/theme/ods-chart-theme.ts
- src/theme/popover/ods-chart-popover.ts
- New feature (non-breaking change which adds functionality)
- Refactoring (non-breaking change)
- Breaking change (fix or feature that would change existing functionality)
> Add Orange Design System look&feel to default Apache ECharts legends

- docs/examples/bar-chart.html
- docs/examples/bar-line-chart.html
- docs/examples/multiple-line-chart.html
- docs/examples/single-line-chart.html
- docs/examples/stacked-bar-chart.html
This PR simply adds a `<main>` HTML tags in all `docs/examples/*` for more semantics.
It has been done in https://github.com/Orange-OpenSource/ods-charts/pull/88/files, but this PR should be merged before for consistency throughout the examples.
> Docs: Use `<main>` HTML tag in examples

- docs/examples/index.js
- docs/use_cases/add-unit.html
- docs/use_cases/size-management.html
- docs/use_cases/specify-color.html
- docs/use_cases/tooltip.html
- docs/use_cases/two-colors-serie.html
- package-lock.json
- package.json
- test/angular-echarts/package-lock.json
- test/angular-echarts/package.json
- test/angular-ngx-echarts/package-lock.json
- test/angular-ngx-echarts/package.json
- test/react/package-lock.json
- test/react/package.json
- test/vue/package-lock.json
- test/vue/package.json
Closes #289
Go through the entire list of the release note to evaluate the impacts, enhancements, etc. we can/must do in ODS Charts. Source: https://github.com/apache/echarts/releases/tag/5.5.1:
- this [new `customValues` for `axisTick` and `axisLabel`](https://echarts.apache.org/en/option.html#xAxis.axisTick.customValues) doesn't have any impact on the library, since it's a new option.
- there's no issue to create in our repository, as it's not something we could introduce by default for our rendering.
- this [new `startValue` option](https://echarts.apache.org/en/option.html#yAxis.startValue) doesn't have any impact on the library, since it's a new option.
- there's no issue to create in our repository, as it's not something we could introduce by default for our rendering.
- this new …
> Bump Apache ECharts from 5.5.0 to 5.5.1

- docs/use_cases/index.html
- docs/use_cases/time-slider.html
- src/theme/ODS.project.ts
https://github.com/Orange-OpenSource/ods-charts/issues/307
- Fix the bug
- Add an example
Sliders are not visibles when using datazoom echarts functionnality
> 307 datazoom not displayed correctly

- README.md
- docs/examples/index.js
In exemple pages add a selector for the renderer SVG or CANVAS
Test and see that theme configurator works fine with both SVG and CANVAS
- New feature (non-breaking change which adds functionality)
> docs(examples): Add availibility to choose between canvas and svg

- src/theme/ods-chart-theme.ts
Remove optional dataOptions in features methods as it can and should be set through `setDataOptions()` call
Simplifications
- Breaking change (fix or feature that would change existing functionality)
> feat(lib)!: Simplify API, removal of optional and duplicate parameters in functionality methods

- docs/use_cases/tooltip.html
… page was missing a little space.
N/A
The Y-axis at the top of some graphs on the tooltip example page was missing a little space.
Display full number on axis:
> fix(doc): The Y-axis at the top of some graphs on the tooltip example page was missing a little space.

- src/theme/colors/colors-css-variables.ts
https://github.com/Orange-OpenSource/ods-charts/issues/534
Change `--ods-pink-dark`
Dark and supportited pink was identical
- Bug fix
> fix(lib): Pink color of SUPPORTING_COLORS and DARKER_TINTS are the same

- docs/assets/color-mode.js
- docs/colors/index.html
- docs/colors/index.js
- docs/index.html
- src/theme/colors/colors-css-variables.ts
next to issue #534 
Add a page to display the set of colors available in ODS Charts
Doing so detect the bug :  The second color of the one color set was not suitable for the dark theme mode.
Display, fix and check color sets
- Bug fix 
- New feature 
> fix(lib): The second color of the same color chart was not suitable for the dark theme mode.

- src/theme/popover/ods-chart-popover.ts
https://github.com/Orange-OpenSource/ods-charts/issues/540
- classes added at the top level of the Apache Echarts popover container are not changed after a switch of dark or light theme mode. This dark or light mode must not be changed at this top level
- A provide formatter may be used to diplay popover content. But after a dark or light mode, the generated formatter must not be consider as user providded one.
1. Popover not readable after them mode switch
2. Popover content replace by `[object HtmlDivElement]` after a mode switch
- Bug fix
> fix(lib): dark/light mode change partially done when using ODSCharts popover renderer

- docs/use_cases/add-unit.html
- docs/use_cases/index.html
- docs/use_cases/legends-holders.html
- docs/use_cases/size-management.html
- docs/use_cases/specify-color.html
- docs/use_cases/theme.html
- docs/use_cases/time-slider.html
- docs/use_cases/tooltip.html
- docs/use_cases/two-colors-serie.html
Provides a new use case page on ODS Charts options to choose the theme provider.
Options may be complex between options for:
- CSS theme , 
- popover renderer 
- dark/light mode
- New feature
> docs: add CSS, dark/light mode and popover theme use cases

- src/theme/resize/ods-chart-resize.ts
https://github.com/Orange-OpenSource/ods-charts/issues/559
By default ECharts has a display animation effect when drawing a chart.
But when you are using the `resize()` method on a chart, this default animation effect is ignored and it uses a specific animation configuration that need to be passed as a parameter to the `resize()` method (cf https://echarts.apache.org/en/api.html#echartsInstance.resize).
If you give no animation effect to be run to the `resize()` method, the display without any effect.
The ODS Charts libray uses the  `resize()` method in the [manageChartResize()](https://ods-charts.netlify.app/api/classes/odschartstheme#managechartresize) feature to redraw the graph
This fix uses the default animation effect set at the graph level when using the `resize()` method
Keep the …
> fix(lib): graph size supervision removed the graph display animation effect

- src/theme/ods-chart-theme.ts
- src/theme/popover/ods-chart-popover.ts
https://github.com/Orange-OpenSource/ods-charts/issues/588
Add error management on the thought error `Cannot read properties of undefined (reading 'pageY')`.
Add error management on every ODS Charts features initialisation
Error at initialisation breaks the charts interactions
> fix(lib): a mouse event during initialisation creates a popover/tooltip errorand disables the legend interaction
